import React from 'react';

export default function TermsOfServicePage() {
    return (
        <div className="max-w-4xl mx-auto py-12 px-8 text-white">
            <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
            <div className="prose prose-invert max-w-none space-y-6 text-black">
                <p><strong>Effective Date:</strong> November 24, 2025<br />
                    <strong>Provider:</strong> UMedia2, Inc.<br />
                    <strong>Registered Address:</strong> 8 The Green, Suite B, Dover, DE, USA, Zip Code 19901<br />
                    <strong>Jurisdiction:</strong> The State of Delaware, United States of America</p>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">1. Introduction and Acceptance of Terms</h2>
                    <p>These Terms of Service govern access to and use of the Kaivo software platform, associated applications, application programming interfaces, data services, analytics systems, and all related technologies provided by UMedia2, Inc. Users who access or use any portion of the Kaivo platform acknowledge that they have read, understood, and agreed to these Terms of Service. Users who do not agree to these Terms of Service must discontinue use immediately.</p>
                    <p>Kaivo is a sophisticated advertising and intelligence platform that processes large scale data sets, optimization signals, campaign performance outputs, and behavioral information in order to deliver high quality advertising results. Users who access this environment agree to strict data rights held by UMedia2, Inc. and consent to extensive operational use of all data processed by the platform.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">2. Definitions</h2>
                    <p>For clarity, the following terms have the meanings set forth below.</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>“Platform”</strong> means the Kaivo software platform, including all components, systems, APIs, algorithms, tools, and features.</li>
                        <li><strong>“User Content”</strong> means creative assets, text, images, videos, data inputs, account information, or other materials provided by the user.</li>
                        <li><strong>“Operational Data”</strong> means logs, metrics, impressions, clicks, campaign results, behavior signals, optimization outputs, routing events, and other system-generated information produced during use of the platform.</li>
                        <li><strong>“Derived Intelligence”</strong> means anonymized data sets, aggregated results, benchmarks, models, predictions, translations, optimization outputs, trend analyses, performance scoring, workflow analytics, and any information generated by UMedia2, Inc. through use of the Platform.</li>
                        <li><strong>“Confidential Information”</strong> means nonpublic information disclosed by either party in connection with use of the Platform.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">3. Eligibility and Compliance</h2>
                    <p>Users must be at least eighteen years old and must have the legal capacity to enter a binding contract. Users must comply with all applicable laws, regulations, and advertising venue policies when using the Platform.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">4. Platform Access and License</h2>
                    <p>UMedia2, Inc. grants users a limited, revocable, nonexclusive, and nontransferable license to access and use the Platform solely for lawful business purposes. UMedia2, Inc. may modify, suspend, or terminate any aspect of the Platform without liability.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">5. User Responsibilities</h2>
                    <p>Users must:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Provide accurate account information.</li>
                        <li>Maintain the confidentiality of account credentials.</li>
                        <li>Ensure compliance with all venue policies.</li>
                        <li>Ensure all User Content complies with applicable law.</li>
                        <li>Refrain from disrupting or interfering with any portion of the Platform.</li>
                    </ul>
                    <p className="mt-4">Users are responsible for all activity conducted under their accounts.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">6. Data Rights and License to User Content</h2>
                    <p>Users retain ownership of their original creative assets and personal information.</p>
                    <p>Users grant UMedia2, Inc. a broad, worldwide, royalty free, irrevocable, sublicensable, transferable license to host, store, transmit, process, reproduce, modify, analyze, display, translate, optimize, and otherwise use User Content for the following purposes:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Campaign execution</li>
                        <li>Reporting</li>
                        <li>Troubleshooting</li>
                        <li>Fraud prevention</li>
                        <li>Model refinement</li>
                        <li>Benchmark development</li>
                        <li>System improvement</li>
                        <li>Research and development</li>
                        <li>Future product innovation</li>
                    </ul>
                    <p className="mt-4">The license continues for as long as UMedia2, Inc. retains any portion of the data in accordance with the Privacy Policy.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">7. Ownership of Derived Intelligence</h2>
                    <p>UMedia2, Inc. retains exclusive ownership of all Derived Intelligence. Users have no ownership interest in or claim to any Derived Intelligence.</p>
                    <p>Derived Intelligence may be created from:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Campaign performance</li>
                        <li>System logs</li>
                        <li>Machine learning processes</li>
                        <li>Optimization workflows</li>
                        <li>Translation or modeling systems</li>
                        <li>Behavioral analytics</li>
                        <li>Aggregated trends</li>
                        <li>Anonymized metrics</li>
                        <li>Any other platform activity</li>
                    </ul>
                    <p className="mt-4">UMedia2, Inc. may use Derived Intelligence for any business purpose, including platform improvement, commercial development, and research.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">8. Prohibited Conduct</h2>
                    <p>Users must not:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>Access the Platform in a manner that circumvents authentication.</li>
                        <li>Reverse engineer or attempt to derive source code.</li>
                        <li>Misuse data provided by any advertising venue.</li>
                        <li>Upload harmful, illegal, or infringing content.</li>
                        <li>Use the Platform for fraudulent activity.</li>
                        <li>Interfere with security or performance of the Platform.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">9. Fees and Billing</h2>
                    <p>Users agree to pay all fees associated with the Platform. Fees may include campaign fees, optimization fees, data processing fees, or other charges. All payments are final unless required by applicable law.</p>
                    <p>Nonpayment may result in suspension or termination of access.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">10. Confidentiality</h2>
                    <p>Each party agrees to protect the other party’s Confidential Information and will not disclose such information except as required by law or expressly permitted under these Terms of Service.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">11. Disclaimer of Warranties</h2>
                    <p>The Platform is provided on an “as is” and “as available” basis. UMedia2, Inc. disclaims all warranties to the maximum extent permitted by law, including warranties of performance, accuracy, or fitness for a particular purpose.</p>
                    <p>UMedia2, Inc. does not guarantee campaign approval, campaign performance, revenue outcomes, or other business results.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">12. Limitation of Liability</h2>
                    <p>UMedia2, Inc. is not liable for indirect, incidental, consequential, or punitive damages. Total liability for all claims will not exceed the amount paid by the user during the twelve month period preceding the claim.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">13. Indemnification</h2>
                    <p>Users agree to indemnify, defend, and hold harmless UMedia2, Inc. and its officers, directors, employees, and contractors from any claim arising out of:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>User Content</li>
                        <li>Misuse of the Platform</li>
                        <li>Violation of these Terms</li>
                        <li>Violation of venue policies</li>
                        <li>Violation of applicable law</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">14. Governing Law; Dispute Resolution</h2>
                    <p>These Terms of Service are governed by the laws of the State of Delaware, United States of America. All disputes will be resolved exclusively in the state or federal courts located in the State of Delaware.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">15. Termination</h2>
                    <p>UMedia2, Inc. may suspend or terminate access to the Platform at any time for cause, nonpayment, or security concerns. Users may stop using the Platform at any time.</p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold text-white mt-8 mb-4">16. Contact Information</h2>
                    <p>UMedia2, Inc.<br />
                        8 The Green, Suite B<br />
                        Dover, DE, USA<br />
                        Zip Code 19901<br />
                        <a href="mailto:info@getkaivo.com" className="text-kaivo-teal-neon hover:underline">info@getkaivo.com</a></p>
                </section>
            </div>
        </div>
    );
}
