"""add spotify agency/client fields

Revision ID: 0556478af300
Revises: 013_reddit_agency_columns
Create Date: 2026-03-31 18:37:10.194106
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0556478af300'
down_revision: Union[str, None] = '013_reddit_agency_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_account_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_licenses_account_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_user_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('idx_saved_variants_user_id'), table_name='saved_variants')
    op.drop_table('saved_variants')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_table('accounts')
    op.add_column('agencies', sa.Column('spotify_agency_access_token', sa.Text(), nullable=True))
    op.add_column('agencies', sa.Column('spotify_refresh_token', sa.Text(), nullable=True))
    op.add_column('agencies', sa.Column('spotify_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agencies', sa.Column('spotify_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('agency_invites_token_key'), 'agency_invites', type_='unique')
    op.create_index(op.f('ix_agency_invites_token'), 'agency_invites', ['token'], unique=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_agency_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('clients', sa.Column('agency_spotify_account_id', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('spotify_account_status', sa.String(length=30), nullable=True))
    op.add_column('clients', sa.Column('spotify_account_name', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('spotify_linked_at', sa.DateTime(timezone=True), nullable=True))
    # NOTE: leaving existing magic_tokens.role and related FKs/indexes as-is to avoid type cast issues on existing data.
    op.drop_index(op.f('ix_plans_account_id'), table_name='plans')
    op.create_index(op.f('ix_plans_client_id'), 'plans', ['client_id'], unique=False)
    op.drop_column('plans', 'account_id')
    op.add_column('platform_credentials', sa.Column('ad_account_id', sa.String(length=255), nullable=True))
    op.add_column('platform_credentials', sa.Column('ad_account_name', sa.String(length=255), nullable=True))
    op.add_column('platform_credentials', sa.Column('currency', sa.String(length=50), nullable=True))
    op.add_column('platform_credentials', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('shopify_connections_shop_domain_key'), 'shopify_connections', type_='unique')
    op.drop_index(op.f('ix_shopify_connections_shop_domain'), table_name='shopify_connections')
    op.create_index(op.f('ix_shopify_connections_shop_domain'), 'shopify_connections', ['shop_domain'], unique=True)
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_shopify_connections_shop_domain'), table_name='shopify_connections')
    op.create_index(op.f('ix_shopify_connections_shop_domain'), 'shopify_connections', ['shop_domain'], unique=False)
    op.create_unique_constraint(op.f('shopify_connections_shop_domain_key'), 'shopify_connections', ['shop_domain'], postgresql_nulls_not_distinct=False)
    op.drop_column('platform_credentials', 'status')
    op.drop_column('platform_credentials', 'currency')
    op.drop_column('platform_credentials', 'ad_account_name')
    op.drop_column('platform_credentials', 'ad_account_id')
    op.add_column('plans', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_plans_client_id'), table_name='plans')
    op.create_index(op.f('ix_plans_account_id'), 'plans', ['account_id'], unique=False)
    op.drop_constraint(None, 'magic_tokens', type_='foreignkey')
    op.drop_constraint(None, 'magic_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('magic_tokens_agency_id_fkey'), 'magic_tokens', 'agencies', ['agency_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('magic_tokens_invited_by_user_id_fkey'), 'magic_tokens', 'users', ['invited_by_user_id'], ['id'], ondelete='SET NULL')
    # Keep existing magic_tokens schema unchanged on downgrade for safety.
    op.drop_column('clients', 'spotify_linked_at')
    op.drop_column('clients', 'spotify_account_name')
    op.drop_column('clients', 'spotify_account_status')
    op.drop_column('clients', 'agency_spotify_account_id')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_agency_id'), 'audit_logs', ['agency_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_agency_invites_token'), table_name='agency_invites')
    op.create_unique_constraint(op.f('agency_invites_token_key'), 'agency_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('agencies', 'spotify_connected_at')
    op.drop_column('agencies', 'spotify_token_expires_at')
    op.drop_column('agencies', 'spotify_refresh_token')
    op.drop_column('agencies', 'spotify_agency_access_token')
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tier', postgresql.ENUM('FREE', 'STARTER', 'GROWTH', 'SCALE', 'ENTERPRISE', name='tierenum'), server_default=sa.text("'FREE'::tierenum"), autoincrement=False, nullable=True),
    sa.Column('monthly_spend', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('billing_status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('parent_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], name=op.f('accounts_parent_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('saved_variants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brief', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('objective', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_lang', sa.VARCHAR(length=10), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True),
    sa.Column('variants_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('saved_variants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_variants_pkey'))
    )
    op.create_index(op.f('idx_saved_variants_user_id'), 'saved_variants', ['user_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('owner', 'manager', 'analyst', 'billing', name='roleenum'), server_default=sa.text("'owner'::roleenum"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('licenses_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('licenses_pkey'))
    )
    op.create_index(op.f('ix_licenses_user_id'), 'licenses', ['user_id'], unique=False)
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_index(op.f('ix_licenses_account_id'), 'licenses', ['account_id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('credits', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('brands_account_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brands_pkey'))
    )
    op.create_index(op.f('ix_brands_account_id'), 'brands', ['account_id'], unique=False)
    # ### end Alembic commands ###

