"""harden_contracts_and_unify_models

Revision ID: 4cacb7fbd509
Revises: 
Create Date: 2025-12-16 23:34:32.435651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4cacb7fbd509'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Idempotent Enum Creation using PostgreSQL DO blocks
    # This avoids DuplicateObject errors and ensures types exist for create_table
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute("""
            DO $$ BEGIN
                CREATE TYPE plantier AS ENUM ('FREE', 'STARTER', 'GROWTH', 'SCALE', 'ENTERPRISE');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)
        op.execute("""
            DO $$ BEGIN
                CREATE TYPE planstatus AS ENUM ('DRAFT', 'CONVERTED');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)
        op.execute("""
            DO $$ BEGIN
                CREATE TYPE agencyrole AS ENUM ('ADMIN', 'MEMBER', 'VIEWER');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)
        op.execute("""
            DO $$ BEGIN
                CREATE TYPE clientrole AS ENUM ('OPERATOR', 'VIEWER');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)
        op.execute("""
            DO $$ BEGIN
                CREATE TYPE invoicestatus AS ENUM ('DRAFT', 'SENT', 'PAID', 'OVERDUE');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)
        op.execute("""
            DO $$ BEGIN
                CREATE TYPE campaignstatus AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'DISABLED', 'COMPLETED', 'ERROR');
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)

    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent table creation - check if table exists first
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'agencies' not in existing_tables:
        op.create_table('agencies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('stripe_customer_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('current_plan', postgresql.ENUM('FREE', 'STARTER', 'GROWTH', 'SCALE', 'ENTERPRISE', name='plantier', create_type=False), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agencies_id'), 'agencies', ['id'], unique=False)
        op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=False)
    
    if 'plans' not in existing_tables:
        op.create_table('plans',
        sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('total_budget_cents', sa.Integer(), nullable=True),
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.Column('platform_allocations_json', sa.JSON(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'CONVERTED', name='planstatus', create_type=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_plans_account_id'), 'plans', ['account_id'], unique=False)
        op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    
    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    if 'agency_memberships' not in existing_tables:
        op.create_table('agency_memberships',
        sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MEMBER', 'VIEWER', name='agencyrole', create_type=False), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_agency_memberships_id'), 'agency_memberships', ['id'], unique=False)
    
    if 'clients' not in existing_tables:
        op.create_table('clients',
        sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('markup_percent', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
        op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    
    if 'audiences' not in existing_tables:
        op.create_table('audiences',
        sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('definition_json', sa.JSON(), nullable=True),
    sa.Column('platform_audience_ids_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_audiences_account_id'), 'audiences', ['account_id'], unique=False)
        op.create_index(op.f('ix_audiences_id'), 'audiences', ['id'], unique=False)
    
    if 'client_memberships' not in existing_tables:
        op.create_table('client_memberships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('role', postgresql.ENUM('OPERATOR', 'VIEWER', name='clientrole', create_type=False), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_client_memberships_id'), 'client_memberships', ['id'], unique=False)
    
    if 'client_user_permissions' not in existing_tables:
        op.create_table('client_user_permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_client_user_permissions_id'), 'client_user_permissions', ['id'], unique=False)
        op.create_index(op.f('ix_client_user_permissions_user_id'), 'client_user_permissions', ['user_id'], unique=False)
    
    if 'invoices' not in existing_tables:
        op.create_table('invoices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('agency_id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
        sa.Column('plan_id', sa.String(), nullable=True),
        sa.Column('platform_fees_total', sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column('kaivo_fees_total', sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column('agency_markup_total', sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column('grand_total', sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column('status', postgresql.ENUM('DRAFT', 'SENT', 'PAID', 'OVERDUE', name='invoicestatus', create_type=False), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    
    if 'platform_accounts' not in existing_tables:
        op.create_table('platform_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('platform', sa.String(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('access_token', sa.String(), nullable=True),
        sa.Column('refresh_token', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_platform_accounts_id'), 'platform_accounts', ['id'], unique=False)
    
    if 'campaigns' not in existing_tables:
        op.create_table('campaigns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=True),
        sa.Column('audience_id', sa.Integer(), nullable=True),
        sa.Column('plan_id', sa.Integer(), nullable=True),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('goal', sa.String(), nullable=False),
        sa.Column('total_budget_cents', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'DISABLED', 'COMPLETED', 'ERROR', name='campaignstatus', create_type=False), nullable=True),
        sa.Column('platform_allocations', sa.JSON(), nullable=True),
        sa.Column('platform_campaign_ids', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['audience_id'], ['audiences.id'], ),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
        sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
        op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    
    if 'usage_records' not in existing_tables:
        op.create_table('usage_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('campaign_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('platform', sa.String(), nullable=False),
        sa.Column('impressions', sa.Integer(), nullable=True),
        sa.Column('clicks', sa.Integer(), nullable=True),
        sa.Column('spend_base', sa.DECIMAL(precision=12, scale=4), nullable=True),
        sa.Column('spend_kaivo', sa.DECIMAL(precision=12, scale=4), nullable=True),
        sa.Column('spend_agency', sa.DECIMAL(precision=12, scale=4), nullable=True),
        sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_platform_accounts_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_client_user_permissions_user_id'), table_name='client_user_permissions')
    op.drop_index(op.f('ix_client_user_permissions_id'), table_name='client_user_permissions')
    op.drop_table('client_user_permissions')
    op.drop_index(op.f('ix_client_memberships_id'), table_name='client_memberships')
    op.drop_table('client_memberships')
    op.drop_index(op.f('ix_audiences_id'), table_name='audiences')
    op.drop_index(op.f('ix_audiences_account_id'), table_name='audiences')
    op.drop_table('audiences')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_agency_memberships_id'), table_name='agency_memberships')
    op.drop_table('agency_memberships')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_account_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_index(op.f('ix_agencies_id'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
